"use client";

import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiAngular,
  SiRedux,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiBootstrap,
  SiAntdesign,
  SiJest,
  SiGraphql,
  SiGit,
  SiGithub,
  SiVercel,
  SiNetlify,
  SiCloudinary,
  SiPostman,
  SiFigma,
  SiNodedotjs,
  SiPython,
  SiDocker,
  SiWebpack,
  SiNpm,
  SiEslint,
  SiPrettier,
  SiStorybook,
  SiVite,
  SiSass,
  SiExpo,
  SiLinux,
} from "react-icons/si";
import { Code, Globe, TestTube, Database, Terminal, Sparkles, Brain, Smartphone, Zap, Shield, Network, Bug, FileCode } from "lucide-react";

// Map skills to their icon components
const iconComponents: { [key: string]: React.ComponentType<{ className?: string }> } = {
  "JavaScript (ES6+)": SiJavascript,
  TypeScript: SiTypescript,
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  Angular: SiAngular,
  "React Native": SiReact,
  Redux: SiRedux,
  Zustand: Code,
  "Context API": Code,
  Vite: SiVite,
  PWA: Smartphone,
  HTML5: SiHtml5,
  CSS3: SiCss3,
  "Responsive Design": Globe,
  "Tailwind CSS": SiTailwindcss,
  Bootstrap: SiBootstrap,
  "Ant Design": SiAntdesign,
  "SASS/SCSS": SiSass,
  Jest: SiJest,
  Playwright: TestTube,
  "Axe DevTools": TestTube,
  "Google Lighthouse": TestTube,
  "OWASP ZAP": TestTube,
  "REST APIs": Database,
  GraphQL: SiGraphql,
  Axios: Code,
  "React Query": Code,
  Git: SiGit,
  GitHub: SiGithub,
  Docker: SiDocker,
  Webpack: SiWebpack,
  "npm/yarn": SiNpm,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  Storybook: SiStorybook,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  Cloudinary: SiCloudinary,
  Postman: SiPostman,
  Figma: SiFigma,
  VSCode: FileCode,
  Cursor: Terminal,
  "Android Studio": Smartphone,
  Antigravity: Sparkles,
  "AI Coding Tools": Brain,
  "GitHub Copilot": SiGithub,
  ChatGPT: Zap,
  Claude: Brain,
  Expo: SiExpo,
  "Kali Linux": SiLinux,
  Metasploit: Shield,
  Wireshark: Network,
  "Burp Suite": Bug,
  "SQL Injection": Shield,
  Python: SiPython,
};

// Map skills to their icons
export const getSkillIcon = (skill: string) => {
  const IconComponent = iconComponents[skill] || Code;
  return <IconComponent className="w-4 h-4" />;
};
